name: Tikipedia
email: shypangolin@tikipedia.net
description: >
        Welcome to tikipedia- your open source DIY cookbook for overcomplicated cocktails!
theme: jekyll-theme-hacker
markdown: kramdown
